name: SonarCloud Scan

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: mr_empirico_computer_maintenance_data_base
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build + tests + coverage
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: mr_empirico_computer_maintenance_data_base
          DB_USER: postgres
          DB_PASSWORD: admin
        run: ./gradlew clean build jacocoTestReport --refresh-dependencies --no-daemon

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=johancaiced0
            -Dsonar.projectKey=Johancaiced0_empirico_mr
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.java.binaries=build/classes/java/main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
